trigger:
  branches:
    include:
      - main  # Cambia si tu rama es diferente

pool:
  name: 'Mac OS'  # Usa tu agente local

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

steps:
  # Paso obligatorio para descargar tu código fuente
  - checkout: self

  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      goals: 'clean verify'
      options: '-Dwebdriver.driver=chrome'
      publishJUnitResults: true
      testResultsFiles: '**/target/site/serenity/*.xml'

  # Publicar el reporte Serenity como artefacto
  - task: PublishBuildArtifacts@1
    displayName: 'Publicar reporte Serenity'
    inputs:
      PathtoPublish: 'target/site/serenity'
      ArtifactName: 'serenity-report'
      publishLocation: 'Container'